SET IDENTITY_INSERT [dbo].[Livros] ON
INSERT INTO [dbo].[Livros] ([Id], [Titulo], [Subtitulo], [Resumo], [ImagemCapa], [Autor], [Lista]) 
VALUES (1001, 'C# e Visual Studio','Desenvolvimento de aplicações desktop','As tradicionais aplicações desktop que muito sucesso fizeram há alguns anos ainda possuem espaço vital no mercado e na arquitetura tecnológica de muitas empresas. Conhecer bem essas tecnologias e saber desenvolver com elas pode ser o diferencial para a escolha adequada em um projeto.
Neste livro Everton Coimbra de Araújo ensina como desenvolver aplicações desktop através do C# e o Visual Studio, mostrando conceitos fundamentais para qualquer profissional que deseja versatilidade na carreira.', CONVERT(varbinary,oo-scharp.png),' Everton Coimbra de Araújo', 'ParaLer')
SET IDENTITY_INSERT [dbo].[Livros] OFF
(1002, 'Web Services REST com ASP .NET Web API e Windows Azure', '','A utilização de serviços REST é uma tendência que vem crescendo muito nos últimos anos, principalmente em APIs públicas, e ASP.NET Web API é a plataforma ideal para a criação de aplicações RESTful sob a plataforma .NET da Microsoft.
Neste livro, Paulo Siécola aborda a criação de Web Services em C#, utilizando a mais recente tecnologia da Microsoft, ASP.NET Web API. Trata-se de um framework que torna simples a criação de serviços a serem consumidos por uma variada gama de clientes, incluindo browsers, dispositivos móveis ou qualquer equipamento capaz de acessar recursos através de HTTP. Para hospedagem dos serviços que serão gerados ao longo dos projetos deste livro, será utilizada a plataforma de computação nas nuvens Windows Azure, que permite a criação de sites, banco de dados e aplicações.',CONVERT(varbinary,livro-webservices.png),'Paulo Siécola','ParaLer'),
(1003,'Orientação a Objetos em C#','Conceitos e implementações em .NET','Nas últimas décadas, o paradigma da Orientação a Objetos tem servido como alicerce para o desenvolvimento de uma ampla gama de linguagens de programação e de ambientes integrados para o desenvolvimento de sistemas informatizados. É necessária uma compreensão profunda dos conceitos inerentes a este moderno paradigma, bem como saber aplicá-los na prática, para que se consiga maximizar seus benefícios: produzir sistemas bem-estruturados, com boa manutenibilidade e alta produtividade.
Neste livro, Everton Coimbra aborda os elementos conceituais da Orientação a Objetos, demonstrando uma implementação prática na linguagem de programação C#, ilustrada passo a passo no Visual Studio. Você estudará os princípios da Orientação a Objetos, como associações, herança e polimorfismo, a linguagem C#, o Visual Studio, acesso ao banco de dados SQL Server por meio do ADO.NET e uma ainda terá introdução ao desenvolvimento de aplicações desktop e uma solução em camadas.',
CONVERT(varbinary, oo-csharp.png,'Everton Coimbra de Araújo','Lendo')),
(1004, 'Bootstrap 4','Conheça a biblioteca front-end mais utilizada no mundo','Fazer um site elegante nunca foi tão fácil, mesmo para quem não sabe escrever uma linha de CSS e, muito menos, entende como harmonizar cores, balancear elementos e tipografia. O Bootstrap é, resumidamente, um grande arquivo CSS com uma excelente documentação, que possui dezenas e dezenas de componentes prontos. No começo, foi criado pelo Twitter para servir como um guia de estilos em CSS da empresa; hoje, é a biblioteca mais famosa e utilizada no mundo.
Neste livro, Natan Souza ensinará como trabalhar com esta fantástica biblioteca em sua última versão 4 ao montar uma página do zero, a partir de um wireframe. Você verá seus principais componentes, como menu responsivo, grids, painéis e botões, além de aprender a customizar seu tema padrão e algumas boas práticas de HTML5, sempre levando em consideração a semântica do código.
Versões utilizadas: Bootstrap 4',CONVERT(varbinary,'bootstrap4.png') ,'Natan Souza','Lido')